#!/usr/bin/env bash

[ "$#" -lt 2 ] && {
    echo 'Need at least two parameters.'
    exit 2
}

#get current default sink
default_sink=$(pacmd info | grep 'Default sink name' | awk -F ': ' '{print $2}')

for line in "$@"; do
  sink=$(cut -d '=' -f1 <<< "$line")
  name=$(cut -d '=' -f2 <<< "$line")
  [ "$sink" != "$default_sink"  ] && {
    pacmd set-default-sink "$sink"
    #move all streams to new sink
    pacmd list-sink-inputs | grep 'index' | while IFS='\n' read -r line; do
      sink_input_idx=$(awk -F ': ' '{print $2}' <<< "$line")
      pacmd move-sink-input "$sink_input_idx" "$sink"
    done
    #show notif
    notify-send -i 'audio-card' 'Audio output' "$name"
    #write current sink to file
    echo "$name" > ~/.local/share/patog/state.txt
    #update genmon plugin (if provided)
    [ -n $3 ] && sh -c "xfce4-panel --plugin-event=$3:refresh:bool:true"
    exit 0
  }
done