#!/usr/bin/env bash

[ "$#" -lt 2 ] && {
    echo 'Need at least two parameters.'
    exit 2
}

default_sink=$(pacmd info | grep 'Default sink name' | awk -F ': ' '{print $2}')
for line in "$@"; do
  sink=$(cut -d '=' -f1 <<< "$line")
  [ "$sink" != "$default_sink"  ] && {
    #set new default sink and move all inputs to it
    pacmd set-default-sink "$sink"
    pacmd list-sink-inputs | grep 'index' | while IFS='\n' read -r line; do
      sink_input_idx=$(awk -F ': ' '{print $2}' <<< "$line")
      pacmd move-sink-input "$sink_input_idx" "$sink"
    done
    #show notification and update genmon plugin
    name=$(cut -d '=' -f2 <<< "$line")
    notify-send -i 'audio-card' 'Audio output' "$name"
    echo "<txt>$name</txt><tool>Sink name: $sink</tool>" > ~/.local/share/patog/genmon
    [ -n $3 ] && sh -c "xfce4-panel --plugin-event=$3:refresh:bool:true"
    exit 0
  }
done