#!/usr/bin/env bash

[ "$EUID" -ne 0 ] && {
        echo "Error: Must be root." >&2
        exit 1
}

dry_run=0
while getopts ":d:t" opt; do
  case $opt in
    d) backup_dir="$OPTARG"
    ;;
    t) dry_run=1
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

[ -z "${backup_dir+set}" ] && {
        echo "Error: must specify backup dir with -d"
        exit 1
}

echo "Backup directory: $backup_dir"
echo "Dry run: $dry_run"

users_dir='/data/users'
archive_suffix="-bkp.tar.gz"
archive_filename="$(date "+%d-%m-%Y")$archive_suffix"

[ "$dry_run" -eq 1 ] && archive="/dev/null" || archive="$backup_dir/$archive_filename"
tar --acls --xattrs -vcpzf $archive $users_dir

exit
