#!/usr/bin/env bash

[ "$EUID" -ne 0 ] && {
        echo "Error: Must be root." >&2
        exit 1
}

dry_run=0
while getopts ":d:t" opt; do
  case $opt in
    d) backup_dir="$OPTARG"
    ;;
    t) dry_run=1
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

[ -z "${backup_dir+set}" ] && {
        echo "Error: must specify backup dir with -d"
        exit 1
}

echo "Backup directory: $backup_dir"
echo "Dry run: $dry_run"

nc_dir='/var/www/nextcloud'
nc_data_dir='/data/nextcloud'
nc_db_name='nextcloud_db'
users_dir='/data/users'

archive_suffix="-bkp.tar.gz"
archive_filename="$(date "+%d-%m-%Y")$archive_suffix"
db_filename='/tmp/sql_bkp'

sudo -u www-data php $nc_dir/occ maintenance:mode --on

mysqldump --single-transaction --default-character-set=utf8mb4 $nc_db_name > $db_filename

[ "$dry_run" -eq 1 ] && archive="/dev/null" || archive="$backup_dir/$archive_filename"
tar --acls --xattrs -vcpzf $archive \
    $nc_dir/config \
    $nc_dir/themes \
    $nc_data_dir \
    $users_dir \
    $db_filename

sudo -u www-data php $nc_dir/occ maintenance:mode --off

exit
