#!/usr/bin/env bash

[ "$EUID" -ne 0 ] && {
        echo "Error: Must be root." >&2
        exit 1
}

backup_dest='/backup/nightly'

# Backup users
rsync -Aavx /data/users $backup_dest/
# Backup radicale
radicale='/data/radicale'
flock --exclusive $radicale/.Radicale.lock rsync -Aavx $radicale $backup_dest/ --exclude '.Radicale.cache' --exclude '.Radicale.lock' --exclude '.Radicale.tmp-*'

exit
