#!/usr/bin/env bash

[ "$EUID" -ne 0 ] && {
        echo "Error: Must be root." >&2
        exit 1
}

backup_dest='/backup/nightly'

users='/data/users'
radicale='/data/radicale'

rsync -Aavx $users $backup_dest/ --exclude '.Trash*'
flock --exclusive $radicale/.Radicale.lock rsync -Aavx $radicale $backup_dest/ --exclude '.Radicale.cache' --exclude '.Radicale.lock' --exclude '.Radicale.tmp-*'

exit
