#!/usr/bin/env bash

[ "$EUID" -ne 0 ] && {
        echo "Error: Must be root." >&2
        exit 1
}

BACKUP_DIR='/backup/nightly'

# Users
USERS_DIR='/data/users'
rsync -Aavx $USERS_DIR $BACKUP_DIR/

exit
