#!/bin/bash

# exactly two needed to toggle
if [ "$#" -ne 2 ]; then
  echo "Need two parameters."
  exit 2
fi
#first argument is name or id of device to toggle (name is constant, id dynamic)
device=$1
icon=$2
#prints 0 or 1 if it's located at end of "Device Enabled" line
state=$(xinput list-props "$device" | grep "Device Enabled" | grep -o "[01]$")
#toggle device state
if [ "$state" = "0" ]
then
	xinput enable "$device"
	message="On"
else
	xinput disable "$device"
	message="Off"
fi
#notify on off
notify-send -i "$icon" "$device" "$message"