#!/usr/bin/env bash

# Must be run as root
[ "$EUID" -ne 0 ] && {
	echo "Error: Needs to be run as root" >&2
	exit 1
}

# Check if both drives are mounted
mountpoint "/media/backup" && mountpoint "/media/data" || {
	echo "Error: data or backup not mounted." >&2
	exit 1
}	

# Nextcloud backup with maintenance mode
/snap/bin/nextcloud.occ maintenance:mode --on
rsync -av /media/data/files/ /media/backup/files
/snap/bin/nextcloud.occ maintenance:mode --off

# Radicale backup with excluding unnecessary files (https://radicale.org/3.0.html#documentation/storage)
# and locking the filesystem to prevent corruption (https://radicale.org/3.0.html#documentation/storage/locking/linux-shell-scripts)
flock --exclusive /var/lib/radicale/collections/.Radicale.lock rsync -av /var/lib/radicale/collections/collection-root/ /media/backup/radicale/collection-root --exclude '.Radicale.cache*' --exclude '.Radicale.tmp*'

exit
